const footballSeedClasses = [
  {
    title: 'Posiciones y Roles en el Campo',
    category: 'Posiciones',
    level: 'Beginner',
    content: [
      { spanish: 'portero / arquero', english: 'goalkeeper (GK)' },
      { spanish: 'defensa', english: 'defender' },
      { spanish: 'defensa central', english: 'center back (CB)' },
      { spanish: 'defensa central derecho', english: 'right center back (RCB)' },
      { spanish: 'defensa central izquierdo', english: 'left center back (LCB)' },
      { spanish: 'lateral derecho', english: 'right back (RB)' },
      { spanish: 'lateral izquierdo', english: 'left back (LB)' },
      { spanish: 'carrilero', english: 'wing back (RWB / LWB)' },
      { spanish: 'mediocampista', english: 'midfielder' },
      { spanish: 'mediocentro', english: 'central midfielder (CM)' },
      { spanish: 'volante defensivo', english: 'defensive midfielder (CDM)' },
      { spanish: 'extremo derecho', english: 'right winger (RW)' },
      { spanish: 'extremo izquierdo', english: 'left winger (LW)' },
      { spanish: 'delantero centro', english: 'striker (ST)' },
      { spanish: 'falso 9', english: 'false nine' },
    ],
  },
  {
    title: 'Acciones del Juego',
    category: 'Acciones',
    level: 'Beginner',
    content: [
      { spanish: 'pase corto', english: 'short pass' },
      { spanish: 'pase largo', english: 'long pass' },
      { spanish: 'pase filtrado', english: 'through ball' },
      { spanish: 'centro', english: 'cross' },
      { spanish: 'disparo', english: 'shot' },
      { spanish: 'disparo a puerta', english: 'shot on target' },
      { spanish: 'disparo fuera', english: 'shot off target' },
      { spanish: 'gol', english: 'goal' },
      { spanish: 'asistencia', english: 'assist' },
      { spanish: 'regate', english: 'dribble' },
      { spanish: 'entrada limpia', english: 'clean tackle' },
      { spanish: 'control del balón', english: 'ball control' },
      { spanish: 'primer toque', english: 'first touch' },
      { spanish: 'recuperación', english: 'ball recovery' },
      { spanish: 'pérdida de balón', english: 'turnover' },
    ],
  },
  {
    title: 'Reglas y Arbitraje',
    category: 'Arbitraje',
    level: 'Intermediate',
    content: [
      { spanish: 'penal', english: 'penalty kick' },
      { spanish: 'fuera de juego', english: 'offside' },
      { spanish: 'falta', english: 'foul' },
      { spanish: 'mano', english: 'handball' },
      { spanish: 'ventaja', english: 'advantage' },
      { spanish: 'tiro libre directo', english: 'direct free kick' },
      { spanish: 'tiro libre indirecto', english: 'indirect free kick' },
      { spanish: 'saque de esquina', english: 'corner kick' },
      { spanish: 'saque de banda', english: 'throw-in' },
      { spanish: 'saque de meta', english: 'goal kick' },
      { spanish: 'tarjeta amarilla', english: 'yellow card' },
      { spanish: 'tarjeta roja', english: 'red card' },
      { spanish: 'expulsión', english: 'sending off' },
      { spanish: 'árbitro', english: 'referee' },
      { spanish: 'VAR', english: 'video assistant referee' },
    ],
  },
  {
    title: 'Táctica y Estrategia',
    category: 'Táctica',
    level: 'Intermediate',
    content: [
      { spanish: 'formación', english: 'formation' },
      { spanish: 'posesión', english: 'possession' },
      { spanish: 'dominio del juego', english: 'game control' },
      { spanish: 'ritmo del partido', english: 'match tempo' },
      { spanish: 'presión alta', english: 'high press' },
      { spanish: 'presión media', english: 'mid press' },
      { spanish: 'bloque bajo', english: 'low block' },
      { spanish: 'bloque alto', english: 'high block' },
      { spanish: 'contraataque', english: 'counterattack' },
      { spanish: 'transición ofensiva', english: 'offensive transition' },
      { spanish: 'transición defensiva', english: 'defensive transition' },
      { spanish: 'salida de balón', english: 'build-up play' },
      { spanish: 'juego directo', english: 'direct play' },
      { spanish: 'juego posicional', english: 'positional play' },
      { spanish: 'cambio de juego', english: 'switch of play' },
      { spanish: 'amplitud', english: 'width' },
      { spanish: 'profundidad', english: 'depth' },
    ],
  },
  {
    title: 'Análisis y Scouting',
    category: 'Análisis',
    level: 'Advanced',
    content: [
      { spanish: 'posesión (%)', english: 'possession (%)' },
      { spanish: 'tiros', english: 'shots' },
      { spanish: 'tiros a puerta', english: 'shots on target' },
      { spanish: 'pases completados', english: 'completed passes' },
      { spanish: 'precisión de pase', english: 'pass accuracy' },
      { spanish: 'expected goals', english: 'xG' },
      { spanish: 'expected assists', english: 'xA' },
      { spanish: 'duelos ganados', english: 'duels won' },
      { spanish: 'recuperaciones', english: 'recoveries' },
      { spanish: 'intercepciones', english: 'interceptions' },
      { spanish: 'minutos jugados', english: 'minutes played' },
      { spanish: 'goles por partido', english: 'goals per match' },
      { spanish: 'asistencias por partido', english: 'assists per match' },
      { spanish: 'técnico', english: 'technical' },
      { spanish: 'táctico', english: 'tactical' },
      { spanish: 'físico', english: 'physical' },
      { spanish: 'psicológico', english: 'psychological' },
      { spanish: 'liderazgo', english: 'leadership' },
    ],
  },
  {
    title: 'Lenguaje del Comentarista y Diferencias Clave',
    category: 'Comunicación',
    level: 'Advanced',
    content: [
      { spanish: '¡Qué golazo!', english: 'What a goal!' },
      { spanish: '¡Increíble parada!', english: 'What a save!' },
      { spanish: 'partido muy disputado', english: 'very competitive match' },
      { spanish: 'está dominando el partido', english: 'he is dominating the game' },
      { spanish: 'gran jugada colectiva', english: 'great team play' },
      { spanish: 'se la pierde increíblemente', english: 'he misses it unbelievably' },
      { spanish: 'está en fuera de juego', english: 'he is offside' },
      { spanish: 'gran definición', english: 'great finish' },
      { spanish: 'contraataque rápido', english: 'fast counterattack' },
      { spanish: 'ataque posicional', english: 'positional attack' },
      { spanish: 'centro al área', english: 'cross into the box' },
      { spanish: 'balón parado', english: 'set piece' },
      { spanish: 'tiro de esquina corto', english: 'short corner' },
      { spanish: 'fútbol (Europa)', english: 'football' },
      { spanish: 'fútbol (USA)', english: 'soccer' },
      { spanish: 'cancha', english: 'pitch' },
      { spanish: 'campo', english: 'field' },
      { spanish: 'botines', english: 'cleats' },
      { spanish: 'botas de fútbol', english: 'boots' },
    ],
  },
  {
    title: 'Historia y Evolución del Fútbol',
    category: 'Historia',
    level: 'Beginner',
    content: [
      { spanish: 'orígenes del fútbol', english: 'origins of football', definition: 'El fútbol moderno se originó en Inglaterra en 1863 con la fundación de la Football Association (FA).', definitionEn: 'Modern football originated in England in 1863 with the founding of the Football Association (FA).', example: 'Los orígenes del fútbol se remontan al siglo XIX en Inglaterra.', exampleEnglish: 'The origins of football date back to the 19th century in England.' },
      { spanish: 'primeras reglas', english: 'first rules', definition: 'Las primeras 13 reglas del fútbol fueron establecidas por la FA en 1863, prohibiendo el uso de las manos.', definitionEn: 'The first 13 rules of football were established by the FA in 1863, prohibiting the use of hands.', example: 'Las primeras reglas del fútbol prohibían tomar el balón con las manos.', exampleEnglish: 'The first rules of football prohibited carrying the ball with hands.' },
      { spanish: 'FIFA', english: 'FIFA', definition: 'Fédération Internationale de Football Association, fundada en 1904, es el organismo rector del fútbol mundial.', definitionEn: 'Fédération Internationale de Football Association, founded in 1904, is the world governing body of football.', example: 'La FIFA organiza la Copa del Mundo cada cuatro años.', exampleEnglish: 'FIFA organizes the World Cup every four years.' },
      { spanish: 'Copa del Mundo', english: 'World Cup', definition: 'Torneo internacional de selecciones nacionales que se celebra cada cuatro años desde 1930.', definitionEn: 'International tournament of national teams held every four years since 1930.', example: 'La Copa del Mundo es el evento deportivo más visto del planeta.', exampleEnglish: 'The World Cup is the most-watched sporting event on the planet.' },
      { spanish: 'UEFA Champions League', english: 'UEFA Champions League', definition: 'Torneo anual de clubes europeos, considerado la competición de clubes más prestigiosa del mundo.', definitionEn: 'Annual tournament for European clubs, considered the most prestigious club competition in the world.', example: 'La Champions League reúne a los mejores clubes de Europa.', exampleEnglish: 'The Champions League brings together the best clubs in Europe.' },
      { spanish: 'Copa América', english: 'Copa América', definition: 'Torneo de selecciones sudamericanas organizado por CONMEBOL, el más antiguo del mundo (1916).', definitionEn: 'South American national team tournament organized by CONMEBOL, the oldest in the world (1916).', example: 'La Copa América se juega desde 1916.', exampleEnglish: 'The Copa América has been played since 1916.' },
      { spanish: 'balón de fútbol', english: 'football / soccer ball', definition: 'El balón oficial debe tener forma esférica, circunferencia de 68-70 cm y peso de 410-450 gramos.', definitionEn: 'The official ball must be spherical, with a circumference of 68-70 cm and weight of 410-450 grams.', example: 'El balón de fútbol ha evolucionado de cuero a materiales sintéticos.', exampleEnglish: 'The football has evolved from leather to synthetic materials.' },
      { spanish: 'estadio de fútbol', english: 'football stadium', definition: 'Recinto deportivo diseñado para albergar partidos de fútbol, con capacidad desde 5,000 hasta más de 100,000 espectadores.', definitionEn: 'Sports venue designed to host football matches, with capacity from 5,000 to over 100,000 spectators.', example: 'El Estadio Maracaná es uno de los más famosos del mundo.', exampleEnglish: 'The Maracanã Stadium is one of the most famous in the world.' },
      { spanish: 'árbitro asistente', english: 'assistant referee', definition: 'Oficial que ayuda al árbitro principal, ubicado en cada banda, señalando fueras de juego y saques de banda.', definitionEn: 'Official who assists the main referee, positioned on each touchline, signaling offsides and throw-ins.', example: 'El árbitro asistente levantó la bandera indicando fuera de juego.', exampleEnglish: 'The assistant referee raised the flag indicating offside.' },
      { spanish: 'tiempo reglamentario', english: 'regulation time', definition: 'Duración oficial de un partido: 90 minutos divididos en dos tiempos de 45 minutos cada uno.', definitionEn: 'Official duration of a match: 90 minutes divided into two halves of 45 minutes each.', example: 'El partido terminó 2-1 en tiempo reglamentario.', exampleEnglish: 'The match ended 2-1 in regulation time.' },
      { spanish: 'tiempo extra', english: 'extra time', definition: 'Período adicional de 30 minutos (dos tiempos de 15) cuando hay empate en partidos eliminatorios.', definitionEn: 'Additional period of 30 minutes (two 15-minute halves) when there is a draw in knockout matches.', example: 'El partido se fue a tiempo extra tras empatar 1-1.', exampleEnglish: 'The match went to extra time after a 1-1 draw.' },
      { spanish: 'tanda de penales', english: 'penalty shootout', definition: 'Serie de 5 penales por equipo para desempatar un partido después del tiempo extra.', definitionEn: 'Series of 5 penalties per team to break a tie after extra time.', example: 'Argentina ganó la final en tanda de penales.', exampleEnglish: 'Argentina won the final in a penalty shootout.' },
      { spanish: 'mercado de fichajes', english: 'transfer market', definition: 'Período del año en que los clubes pueden comprar y vender jugadores entre sí.', definitionEn: 'Period of the year when clubs can buy and sell players among themselves.', example: 'El mercado de fichajes de verano cierra en agosto.', exampleEnglish: 'The summer transfer market closes in August.' },
      { spanish: 'cláusula de rescisión', english: 'release clause', definition: 'Cantidad de dinero establecida en el contrato de un jugador que un club debe pagar para liberarlo.', definitionEn: 'Amount of money set in a player\'s contract that a club must pay to release him.', example: 'El jugador tiene una cláusula de rescisión de 100 millones.', exampleEnglish: 'The player has a release clause of 100 million.' },
      { spanish: 'cantera / academia', english: 'youth academy', definition: 'Sistema de formación de jóvenes jugadores dentro de un club, también conocida como \'cantera\'.', definitionEn: 'Youth development system within a club, also known as \'quarry\' in Spanish.', example: 'La cantera del Barcelona produce talentos mundialmente conocidos.', exampleEnglish: 'Barcelona\'s youth academy produces world-renowned talents.' },
    ],
  },
  {
    title: 'Reglas Detalladas del Juego',
    category: 'Reglas',
    level: 'Intermediate',
    content: [
      { spanish: 'regla del fuera de juego', english: 'offside rule', definition: 'Un jugador está en fuera de juego si cualquier parte de su cabeza, cuerpo o pies está más cerca de la línea de meta rival que el balón y el penúltimo defensor.', definitionEn: 'A player is in an offside position if any part of their head, body or feet is nearer to the opponent\'s goal line than both the ball and the second-last opponent.', example: 'El delantero estaba en fuera de juego cuando recibió el pase.', exampleEnglish: 'The striker was offside when he received the pass.' },
      { spanish: 'regla del gol', english: 'goal rule', definition: 'Se considera gol cuando el balón cruza completamente la línea de meta entre los postes y por debajo del travesaño.', definitionEn: 'A goal is scored when the ball completely crosses the goal line between the posts and under the crossbar.', example: 'El gol fue validado tras revisión del VAR.', exampleEnglish: 'The goal was validated after VAR review.' },
      { spanish: 'regla del penal', english: 'penalty rule', definition: 'Se sanciona penal cuando un defensor comete una falta dentro de su propia área penal.', definitionEn: 'A penalty is awarded when a defender commits a foul inside their own penalty area.', example: 'El árbitro señaló penal por mano dentro del área.', exampleEnglish: 'The referee awarded a penalty for handball inside the box.' },
      { spanish: 'regla de la mano', english: 'handball rule', definition: 'Es infracción tocar el balón deliberadamente con la mano o brazo, o tener el brazo en posición antinatural que amplíe el espacio del cuerpo.', definitionEn: 'It is an offense to deliberately touch the ball with hand or arm, or to have the arm in an unnatural position that makes the body unnaturally bigger.', example: 'El VAR revisó la jugada por posible mano.', exampleEnglish: 'VAR reviewed the play for a possible handball.' },
      { spanish: 'regla de la ventaja', english: 'advantage rule', definition: 'El árbitro puede permitir que el juego continúe si el equipo perjudicado por una falta mantiene la posesión y tiene oportunidad de atacar.', definitionEn: 'The referee may allow play to continue if the team fouled keeps possession and has an attacking opportunity.', example: 'El árbitro aplicó la ley de la ventaja y el equipo casi marca.', exampleEnglish: 'The referee applied the advantage rule and the team almost scored.' },
      { spanish: 'sustituciones', english: 'substitutions', definition: 'Cada equipo puede realizar hasta 5 sustituciones por partido (3 ventanas de cambio, más el descanso).', definitionEn: 'Each team can make up to 5 substitutions per match (3 substitution windows, plus halftime).', example: 'El entrenador hizo las 5 sustituciones en el segundo tiempo.', exampleEnglish: 'The coach made all 5 substitutions in the second half.' },
      { spanish: 'tarjeta amarilla por acumulación', english: 'yellow card accumulation', definition: 'Un jugador que recibe dos tarjetas amarillas en un mismo partido es expulsado con tarjeta roja.', definitionEn: 'A player who receives two yellow cards in the same match is sent off with a red card.', example: 'El defensa fue expulsado por doble amarilla.', exampleEnglish: 'The defender was sent off for a double yellow card.' },
      { spanish: 'falta táctica', english: 'tactical foul', definition: 'Falta intencional cometida para detener un contraataque rival, generalmente sancionada con tarjeta amarilla.', definitionEn: 'Intentional foul committed to stop an opponent\'s counterattack, usually punished with a yellow card.', example: 'El mediocampista cometió una falta táctica para cortar el contraataque.', exampleEnglish: 'The midfielder committed a tactical foul to stop the counterattack.' },
      { spanish: 'regla del fuera de juego pasivo', english: 'passive offside', definition: 'Un jugador en posición de fuera de juego no es sancionado si no interfiere en el juego ni obtiene ventaja.', definitionEn: 'A player in an offside position is not penalized if they do not interfere with play or gain an advantage.', example: 'El delantero estaba en fuera de juego pasivo y no fue sancionado.', exampleEnglish: 'The striker was in a passive offside position and was not penalized.' },
      { spanish: 'regla del gol de visitante', english: 'away goals rule', definition: 'Regla (ya abolida en 2021) que daba ventaja al equipo que marcaba más goles como visitante en eliminatorias.', definitionEn: 'Rule (abolished in 2021) that gave advantage to the team scoring more away goals in knockout ties.', example: 'El equipo avanzó por la regla del gol de visitante.', exampleEnglish: 'The team advanced due to the away goals rule.' },
      { spanish: 'VAR (Video Assistant Referee)', english: 'VAR (Video Assistant Referee)', definition: 'Sistema de revisión por video que asiste al árbitro en cuatro tipos de decisiones: goles, penales, tarjetas rojas y identidad del jugador.', definitionEn: 'Video review system that assists the referee in four types of decisions: goals, penalties, red cards, and player identity.', example: 'El VAR revisó la jugada y recomendó revisión en el monitor.', exampleEnglish: 'VAR reviewed the play and recommended an on-field review.' },
      { spanish: 'semi-automated offside', english: 'semi-automated offside technology', definition: 'Tecnología que usa 12 cámaras y un sensor en el balón para detectar automáticamente posiciones de fuera de juego.', definitionEn: 'Technology that uses 12 cameras and a sensor in the ball to automatically detect offside positions.', example: 'La tecnología semi-automated offside aceleró las decisiones de fuera de juego.', exampleEnglish: 'Semi-automated offside technology sped up offside decisions.' },
      { spanish: 'goal-line technology', english: 'goal-line technology', definition: 'Sistema que usa 7 cámaras por arco para determinar si el balón cruzó completamente la línea de gol.', definitionEn: 'System that uses 7 cameras per goal to determine if the ball fully crossed the goal line.', example: 'La goal-line technology confirmó que el balón no entró completamente.', exampleEnglish: 'Goal-line technology confirmed the ball did not fully cross the line.' },
      { spanish: 'fair play financiero', english: 'Financial Fair Play (FFP)', definition: 'Regulación de la UEFA que limita el gasto de los clubes a sus ingresos generados para evitar déficits insostenibles.', definitionEn: 'UEFA regulation that limits club spending to their generated revenue to prevent unsustainable deficits.', example: 'El club fue sancionado por violar el fair play financiero.', exampleEnglish: 'The club was sanctioned for violating Financial Fair Play.' },
      { spanish: 'regla de los 3 puntos', english: 'three-point rule', definition: 'Sistema de puntuación donde el equipo ganador recibe 3 puntos, el perdedor 0, y en empate ambos reciben 1 punto.', definitionEn: 'Scoring system where the winning team receives 3 points, the loser 0, and in a draw both receive 1 point.', example: 'Con la regla de los 3 puntos, ganar es más valioso que empatar.', exampleEnglish: 'With the three-point rule, winning is more valuable than drawing.' },
    ],
  },
  {
    title: 'Grandes Jugadores y Leyendas',
    category: 'Leyendas',
    level: 'Advanced',
    content: [
      { spanish: 'Pelé', english: 'Pelé', definition: 'Edson Arantes do Nascimento, considerado por muchos el mejor jugador de la historia, ganó 3 Copas del Mundo (1958, 1962, 1970).', definitionEn: 'Edson Arantes do Nascimento, considered by many the best player ever, won 3 World Cups (1958, 1962, 1970).', example: 'Pelé marcó más de 1,000 goles en su carrera profesional.', exampleEnglish: 'Pelé scored over 1,000 goals in his professional career.' },
      { spanish: 'Diego Maradona', english: 'Diego Maradona', definition: 'Genio argentino conocido por la \'Mano de Dios\' y el \'Gol del Siglo\' en el Mundial de 1986, que ganó con Argentina.', definitionEn: 'Argentine genius known for the \'Hand of God\' and the \'Goal of the Century\' in the 1986 World Cup, which he won with Argentina.', example: 'Maradona llevó a Argentina a la gloria en el Mundial de 1986.', exampleEnglish: 'Maradona led Argentina to glory in the 1986 World Cup.' },
      { spanish: 'Lionel Messi', english: 'Lionel Messi', definition: 'Delantero argentino, 8 veces ganador del Balón de Oro, campeón del Mundo en 2022, máximo goleador histórico del Barcelona.', definitionEn: 'Argentine forward, 8-time Ballon d\'Or winner, World Champion in 2022, Barcelona\'s all-time top scorer.', example: 'Messi ganó el Mundial de Qatar 2022 con Argentina.', exampleEnglish: 'Messi won the 2022 Qatar World Cup with Argentina.' },
      { spanish: 'Cristiano Ronaldo', english: 'Cristiano Ronaldo', definition: 'Delantero portugués, 5 veces ganador del Balón de Oro, máximo goleador histórico de la Champions League y de selecciones.', definitionEn: 'Portuguese forward, 5-time Ballon d\'Or winner, all-time top scorer in Champions League and international football.', example: 'Cristiano Ronaldo es el máximo goleador de la historia de la Champions.', exampleEnglish: 'Cristiano Ronaldo is the all-time top scorer in Champions League history.' },
      { spanish: 'Johan Cruyff', english: 'Johan Cruyff', definition: 'Leyenda neerlandesa, pionero del \'Fútbol Total\', 3 veces Balón de Oro, revolucionó el Barcelona como jugador y entrenador.', definitionEn: 'Dutch legend, pioneer of \'Total Football\', 3-time Ballon d\'Or winner, revolutionized Barcelona as player and coach.', example: 'Cruyff implementó la filosofía del \'Fútbol Total\' en el Barcelona.', exampleEnglish: 'Cruyff implemented the \'Total Football\' philosophy at Barcelona.' },
      { spanish: 'Zinedine Zidane', english: 'Zinedine Zidane', definition: 'Mediocampista francés, Balón de Oro 1998, campeón del Mundo (1998) y de Europa (2000), luego exitoso entrenador del Real Madrid.', definitionEn: 'French midfielder, 1998 Ballon d\'Or winner, World Cup (1998) and European Championship (2000) winner, later successful Real Madrid coach.', example: 'Zidane ganó 3 Champions League consecutivas como entrenador.', exampleEnglish: 'Zidane won 3 consecutive Champions Leagues as a coach.' },
      { spanish: 'Ronaldo Nazário', english: 'Ronaldo Nazário', definition: 'Delantero brasileño, 2 veces Balón de Oro, campeón del Mundo en 1994 y 2002, conocido como \'El Fenómeno\'.', definitionEn: 'Brazilian striker, 2-time Ballon d\'Or winner, World Cup champion in 1994 and 2002, known as \'The Phenomenon\'.', example: 'Ronaldo Nazário fue el jugador más joven en ganar el Balón de Oro.', exampleEnglish: 'Ronaldo Nazário was the youngest player to win the Ballon d\'Or.' },
      { spanish: 'Alfredo Di Stéfano', english: 'Alfredo Di Stéfano', definition: 'Leyenda argentino-española del Real Madrid, ganó 5 Copas de Europa consecutivas (1956-1960), 2 veces Balón de Oro.', definitionEn: 'Argentine-Spanish legend of Real Madrid, won 5 consecutive European Cups (1956-1960), 2-time Ballon d\'Or winner.', example: 'Di Stéfano es considerado una de las mayores leyendas del Real Madrid.', exampleEnglish: 'Di Stéfano is considered one of Real Madrid\'s greatest legends.' },
      { spanish: 'Franz Beckenbauer', english: 'Franz Beckenbauer', definition: 'Defensa alemán, \'El Káiser\', campeón del Mundo como jugador (1974) y como entrenador (1990), 2 veces Balón de Oro.', definitionEn: 'German defender, \'The Kaiser\', World Cup champion as player (1974) and coach (1990), 2-time Ballon d\'Or winner.', example: 'Beckenbauer inventó la posición de líbero moderno.', exampleEnglish: 'Beckenbauer invented the modern sweeper position.' },
      { spanish: 'Michel Platini', english: 'Michel Platini', definition: 'Mediocampista francés, 3 veces Balón de Oro consecutivo (1983-1985), máximo goleador de la Eurocopa 1984.', definitionEn: 'French midfielder, 3 consecutive Ballon d\'Or winner (1983-1985), top scorer of Euro 1984.', example: 'Platini marcó 9 goles en la Eurocopa de 1984.', exampleEnglish: 'Platini scored 9 goals in the 1984 European Championship.' },
      { spanish: 'George Best', english: 'George Best', definition: 'Extremo norirlandés, Balón de Oro 1968, leyenda del Manchester United, conocido por su increíble regate y talento natural.', definitionEn: 'Northern Irish winger, 1968 Ballon d\'Or winner, Manchester United legend, known for his incredible dribbling and natural talent.', example: 'Best fue uno de los primeros futbolistas en convertirse en icono pop.', exampleEnglish: 'Best was one of the first footballers to become a pop icon.' },
      { spanish: 'Eusébio', english: 'Eusébio', definition: 'Delantero portugués de Mozambique, Balón de Oro 1965, máximo goleador del Mundial 1966 con 9 goles.', definitionEn: 'Portuguese forward from Mozambique, 1965 Ballon d\'Or winner, top scorer of the 1966 World Cup with 9 goals.', example: 'Eusébio marcó 4 goles en un partido del Mundial 1966.', exampleEnglish: 'Eusébio scored 4 goals in one match of the 1966 World Cup.' },
      { spanish: 'Lev Yashin', english: 'Lev Yashin', definition: 'Portero soviético, único portero en ganar el Balón de Oro (1963), conocido como \'La Araña Negra\' por sus reflejos y vestimenta negra.', definitionEn: 'Soviet goalkeeper, only goalkeeper to win the Ballon d\'Or (1963), known as \'The Black Spider\' for his reflexes and black attire.', example: 'Yashin es considerado el mejor portero de la historia.', exampleEnglish: 'Yashin is considered the best goalkeeper in history.' },
      { spanish: 'Paolo Maldini', english: 'Paolo Maldini', definition: 'Defensa italiano, leyenda del AC Milan, ganó 5 Champions League, conocido por su elegancia defensiva y liderazgo.', definitionEn: 'Italian defender, AC Milan legend, won 5 Champions Leagues, known for his defensive elegance and leadership.', example: 'Maldini jugó al más alto nivel hasta los 41 años.', exampleEnglish: 'Maldini played at the highest level until age 41.' },
      { spanish: 'Garrincha', english: 'Garrincha', definition: 'Extremo brasileño, conocido como \'La Alegría del Pueblo\', campeón del Mundo en 1958 y 1962, famoso por sus regates y piernas arqueadas.', definitionEn: 'Brazilian winger, known as \'The Joy of the People\', World Cup champion in 1958 and 1962, famous for his dribbling and bowed legs.', example: 'Garrincha era famoso por sus regates imposibles.', exampleEnglish: 'Garrincha was famous for his impossible dribbles.' },
    ],
  },
  {
    title: 'Competiciones y Torneos',
    category: 'Competiciones',
    level: 'Beginner',
    content: [
      { spanish: 'Copa Mundial de la FIFA', english: 'FIFA World Cup', definition: 'Torneo internacional de selecciones nacionales masculinas organizado por la FIFA cada cuatro años desde 1930.', definitionEn: 'International tournament for men\'s national teams organized by FIFA every four years since 1930.', example: 'La Copa Mundial de la FIFA 2026 se jugará en Estados Unidos, México y Canadá.', exampleEnglish: 'The 2026 FIFA World Cup will be played in the United States, Mexico, and Canada.' },
      { spanish: 'Eurocopa', english: 'UEFA European Championship', definition: 'Campeonato de selecciones nacionales europeas organizado por la UEFA cada cuatro años desde 1960.', definitionEn: 'European national team championship organized by UEFA every four years since 1960.', example: 'España ganó la Eurocopa en 1964, 2008, 2012 y 2024.', exampleEnglish: 'Spain won the European Championship in 1964, 2008, 2012, and 2024.' },
      { spanish: 'Copa Libertadores', english: 'Copa Libertadores', definition: 'Torneo anual de clubes sudamericanos organizado por CONMEBOL, el más prestigioso de América.', definitionEn: 'Annual South American club tournament organized by CONMEBOL, the most prestigious in the Americas.', example: 'La Copa Libertadores es el equivalente sudamericano de la Champions League.', exampleEnglish: 'The Copa Libertadores is South America\'s equivalent of the Champions League.' },
      { spanish: 'UEFA Europa League', english: 'UEFA Europa League', definition: 'Segunda competición europea de clubes en importancia, para equipos que no clasifican a la Champions League.', definitionEn: 'Second most important European club competition, for teams that do not qualify for the Champions League.', example: 'El Sevilla es el equipo más exitoso de la Europa League con 7 títulos.', exampleEnglish: 'Sevilla is the most successful team in the Europa League with 7 titles.' },
      { spanish: 'FA Cup', english: 'FA Cup', definition: 'Torneo de copa más antiguo del mundo, organizado por la Football Association inglesa desde 1871.', definitionEn: 'The oldest cup competition in the world, organized by the English Football Association since 1871.', example: 'La FA Cup es famosa por sus sorpresas cuando equipos pequeños eliminan a gigantes.', exampleEnglish: 'The FA Cup is famous for its upsets when small teams eliminate giants.' },
      { spanish: 'Copa del Rey', english: 'Copa del Rey', definition: 'Torneo de copa nacional de España, organizado por la Real Federación Española de Fútbol desde 1903.', definitionEn: 'Spain\'s national cup tournament, organized by the Royal Spanish Football Federation since 1903.', example: 'El Barcelona es el equipo con más títulos de la Copa del Rey.', exampleEnglish: 'Barcelona is the team with the most Copa del Rey titles.' },
      { spanish: 'Supercopa', english: 'Super Cup', definition: 'Partido o torneo que enfrenta al campeón de liga contra el campeón de copa de una misma temporada.', definitionEn: 'Match or tournament that pits the league champion against the cup champion of the same season.', example: 'La Supercopa de España se juega en Arabia Saudí desde 2020.', exampleEnglish: 'The Spanish Super Cup has been played in Saudi Arabia since 2020.' },
      { spanish: 'Mundial de Clubes', english: 'FIFA Club World Cup', definition: 'Torneo que enfrenta a los campeones de cada confederación continental para determinar el mejor club del mundo.', definitionEn: 'Tournament that pits the champions of each continental confederation to determine the best club in the world.', example: 'El Real Madrid ha ganado el Mundial de Clubes en múltiples ocasiones.', exampleEnglish: 'Real Madrid has won the Club World Cup on multiple occasions.' },
      { spanish: 'Clásico', english: 'El Clásico', definition: 'Partido entre el Real Madrid y el FC Barcelona, considerado la mayor rivalidad del fútbol mundial.', definitionEn: 'Match between Real Madrid and FC Barcelona, considered the greatest rivalry in world football.', example: 'El Clásico es visto por más de 600 millones de personas en todo el mundo.', exampleEnglish: 'El Clásico is watched by over 600 million people worldwide.' },
      { spanish: 'derbi', english: 'derby', definition: 'Partido entre dos equipos de la misma ciudad o región con rivalidad histórica.', definitionEn: 'Match between two teams from the same city or region with historical rivalry.', example: 'El derbi de Milán entre Inter y AC Milan es uno de los más famosos.', exampleEnglish: 'The Milan derby between Inter and AC Milan is one of the most famous.' },
      { spanish: 'fase de grupos', english: 'group stage', definition: 'Primera fase de un torneo donde los equipos se dividen en grupos y juegan entre sí para avanzar a eliminatorias.', definitionEn: 'First phase of a tournament where teams are divided into groups and play each other to advance to knockout rounds.', example: 'La fase de grupos de la Champions League tiene 8 grupos de 4 equipos cada uno.', exampleEnglish: 'The Champions League group stage has 8 groups of 4 teams each.' },
      { spanish: 'eliminatorias', english: 'knockout rounds', definition: 'Fase de un torneo donde los equipos se eliminan mutuamente en partidos directos hasta llegar a la final.', definitionEn: 'Phase of a tournament where teams eliminate each other in direct matches until reaching the final.', example: 'Las eliminatorias de la Champions comienzan en octavos de final.', exampleEnglish: 'The Champions League knockout rounds begin with the round of 16.' },
      { spanish: 'final', english: 'final', definition: 'Partido decisivo que determina al campeón de un torneo o competición.', definitionEn: 'Decisive match that determines the champion of a tournament or competition.', example: 'La final de la Champions League 2025 se jugó en Múnich.', exampleEnglish: 'The 2025 Champions League final was played in Munich.' },
      { spanish: 'pretemporada', english: 'preseason', definition: 'Período de preparación física y táctica antes del inicio de la temporada oficial.', definitionEn: 'Period of physical and tactical preparation before the start of the official season.', example: 'Los equipos realizan giras de pretemporada por diferentes países.', exampleEnglish: 'Teams go on preseason tours to different countries.' },
      { spanish: 'temporada regular', english: 'regular season', definition: 'Período de la liga donde todos los equipos juegan entre sí antes de las fases finales.', definitionEn: 'Period of the league where all teams play each other before the final phases.', example: 'La temporada regular de La Liga tiene 38 jornadas.', exampleEnglish: 'La Liga\'s regular season has 38 matchdays.' },
    ],
  },
  {
    title: 'Equipamiento y Vestimenta Deportiva',
    category: 'Equipamiento',
    level: 'Beginner',
    content: [
      { spanish: 'camiseta', english: 'jersey / shirt', definition: 'Prenda principal del uniforme de fútbol, con los colores del club y el número del jugador.', definitionEn: 'Main garment of the football uniform, with the club colors and player number.', example: 'La camiseta del Barcelona es azul y grana con rayas verticales.', exampleEnglish: 'Barcelona\'s jersey is blue and maroon with vertical stripes.' },
      { spanish: 'pantalón corto', english: 'shorts', definition: 'Prenda inferior del uniforme de fútbol, generalmente del mismo color que la camiseta.', definitionEn: 'Lower garment of the football uniform, usually the same color as the jersey.', example: 'Los pantalones cortos del Real Madrid son blancos como la camiseta.', exampleEnglish: 'Real Madrid\'s shorts are white like the jersey.' },
      { spanish: 'medias', english: 'socks', definition: 'Prenda que cubre desde el pie hasta la rodilla, usada sobre las espinilleras.', definitionEn: 'Garment covering from foot to knee, worn over the shin guards.', example: 'Las medias de fútbol suelen llegar hasta la rodilla.', exampleEnglish: 'Football socks usually reach up to the knee.' },
      { spanish: 'botines / botas de fútbol', english: 'cleats / boots', definition: 'Calzado especial con tacos en la suela para proporcionar tracción en el césped.', definitionEn: 'Special footwear with studs on the sole to provide traction on grass.', example: 'Los botines modernos son ultraligeros y están hechos de materiales sintéticos.', exampleEnglish: 'Modern cleats are ultralight and made of synthetic materials.' },
      { spanish: 'espinilleras / canilleras', english: 'shin guards', definition: 'Protector plástico colocado debajo de las medias para proteger la espinilla de golpes.', definitionEn: 'Plastic protector placed under the socks to protect the shin from impacts.', example: 'Las espinilleras son obligatorias en todos los partidos oficiales.', exampleEnglish: 'Shin guards are mandatory in all official matches.' },
      { spanish: 'guantes de portero', english: 'goalkeeper gloves', definition: 'Guantes acolchados con látex que usa el portero para proteger sus manos y mejorar el agarre del balón.', definitionEn: 'Padded latex gloves worn by the goalkeeper to protect hands and improve ball grip.', example: 'Los guantes de portero tienen látex en la palma para mejor agarre.', exampleEnglish: 'Goalkeeper gloves have latex on the palm for better grip.' },
      { spanish: 'balón', english: 'ball', definition: 'Implemento esférico con el que se juega al fútbol, de 68-70 cm de circunferencia y 410-450 gramos.', definitionEn: 'Spherical implement used to play football, 68-70 cm in circumference and 410-450 grams.', example: 'El balón oficial de la Champions League tiene estrellas características.', exampleEnglish: 'The official Champions League ball has characteristic stars.' },
      { spanish: 'red de la portería', english: 'goal net', definition: 'Malla colocada detrás de la portería para detener el balón cuando entra y confirmar visualmente el gol.', definitionEn: 'Net placed behind the goal to stop the ball when it enters and visually confirm the goal.', example: 'La red de la portería se rompió tras un disparo potente.', exampleEnglish: 'The goal net broke after a powerful shot.' },
      { spanish: 'banderín de esquina', english: 'corner flag', definition: 'Poste con bandera ubicado en cada esquina del campo que delimita el área de saque de esquina.', definitionEn: 'Flag post located at each corner of the field that marks the corner kick area.', example: 'El banderín de esquina debe tener al menos 1.5 metros de altura.', exampleEnglish: 'The corner flag must be at least 1.5 meters high.' },
      { spanish: 'silbato', english: 'whistle', definition: 'Instrumento que usa el árbitro para señalar el inicio, detención y reanudación del juego.', definitionEn: 'Instrument used by the referee to signal the start, stop, and restart of play.', example: 'El árbitro hizo sonar el silbato para indicar el final del partido.', exampleEnglish: 'The referee blew the whistle to signal the end of the match.' },
      { spanish: 'tarjeta', english: 'card', definition: 'Cartulina amarilla o roja que muestra el árbitro para sancionar infracciones disciplinarias.', definitionEn: 'Yellow or red card shown by the referee to sanction disciplinary infractions.', example: 'El árbitro sacó tarjeta amarilla por la falta temeraria.', exampleEnglish: 'The referee showed a yellow card for the reckless foul.' },
      { spanish: 'cinta de capitán', english: 'captain\'s armband', definition: 'Brazalete que identifica al capitán del equipo en el campo de juego.', definitionEn: 'Armband that identifies the team captain on the field of play.', example: 'La cinta de capitán del Barcelona la lleva actualmente el defensa central.', exampleEnglish: 'Barcelona\'s captain\'s armband is currently worn by the center back.' },
      { spanish: 'peto / chaleco', english: 'bib / vest', definition: 'Prenda sin mangas de colores vivos usada en entrenamientos para distinguir equipos.', definitionEn: 'Sleeveless garment in bright colors used in training to distinguish teams.', example: 'Los jugadores usan petos amarillos y rojos en los entrenamientos.', exampleEnglish: 'Players wear yellow and red bibs during training sessions.' },
      { spanish: 'conos', english: 'cones', definition: 'Objetos cónicos de plástico usados en entrenamiento para marcar espacios y realizar ejercicios.', definitionEn: 'Plastic cone-shaped objects used in training to mark spaces and perform drills.', example: 'El entrenador colocó conos para el ejercicio de regate.', exampleEnglish: 'The coach placed cones for the dribbling drill.' },
      { spanish: 'caballete / valla', english: 'hurdle', definition: 'Obstáculo bajo usado en entrenamiento físico para mejorar la agilidad y coordinación del jugador.', definitionEn: 'Low obstacle used in physical training to improve player agility and coordination.', example: 'Los jugadores saltaron vallas como parte del calentamiento.', exampleEnglish: 'The players jumped over hurdles as part of the warm-up.' },
    ],
  },
  {
    title: 'Aficionados y Cultura del Fútbol',
    category: 'Cultura',
    level: 'Intermediate',
    content: [
      { spanish: 'hincha / aficionado', english: 'fan / supporter', definition: 'Persona que sigue y apoya a un equipo de fútbol con pasión y lealtad.', definitionEn: 'Person who follows and supports a football team with passion and loyalty.', example: 'Los hinchas del equipo llenaron el estadio para apoyar a su club.', exampleEnglish: 'The team\'s fans filled the stadium to support their club.' },
      { spanish: 'barra brava / ultra', english: 'ultras / firm', definition: 'Grupo organizado de aficionados radicales que animan intensamente a su equipo, a menudo con coreografías y cánticos.', definitionEn: 'Organized group of radical fans who intensely support their team, often with choreography and chants.', example: 'La barra brava del equipo preparó un tifo espectacular para la final.', exampleEnglish: 'The team\'s ultras prepared a spectacular tifo for the final.' },
      { spanish: 'cántico', english: 'chant', definition: 'Canción o grito rítmico entonado por los aficionados durante los partidos para animar a su equipo.', definitionEn: 'Song or rhythmic shout sung by fans during matches to encourage their team.', example: 'Los aficionados corearon cánticos durante todo el partido.', exampleEnglish: 'The fans chanted songs throughout the entire match.' },
      { spanish: 'tifo', english: 'tifo', definition: 'Coreografía visual realizada por los aficionados en las gradas usando pancartas, mosaicos y globos.', definitionEn: 'Visual choreography performed by fans in the stands using banners, mosaics, and balloons.', example: 'El tifo cubrió toda una grada con los colores del club.', exampleEnglish: 'The tifo covered an entire stand with the club\'s colors.' },
      { spanish: 'bufanda', english: 'scarf', definition: 'Prenda de vestir con los colores del equipo que los aficionados usan y ondean durante los partidos.', definitionEn: 'Garment with team colors that fans wear and wave during matches.', example: 'Los aficionados levantaron sus bufandas al unísono antes del partido.', exampleEnglish: 'The fans raised their scarves in unison before the match.' },
      { spanish: 'estadio lleno', english: 'sell-out crowd', definition: 'Situación en la que todas las entradas de un estadio se han vendido para un partido.', definitionEn: 'Situation where all tickets for a match at a stadium have been sold.', example: 'El partido se jugó con estadio lleno y 80,000 espectadores.', exampleEnglish: 'The match was played with a sell-out crowd of 80,000 spectators.' },
      { spanish: 'localía / ventaja de local', english: 'home advantage', definition: 'Ventaja que tiene el equipo local al jugar en su estadio con el apoyo de su afición.', definitionEn: 'Advantage that the home team has when playing in their stadium with the support of their fans.', example: 'La localía es muy importante en los partidos de eliminatorias.', exampleEnglish: 'Home advantage is very important in knockout matches.' },
      { spanish: 'entrada / boleto', english: 'ticket', definition: 'Documento que permite el acceso al estadio para presenciar un partido de fútbol.', definitionEn: 'Document that grants access to the stadium to watch a football match.', example: 'Las entradas para el clásico se agotaron en una hora.', exampleEnglish: 'Tickets for the clásico sold out in one hour.' },
      { spanish: 'abono', english: 'season ticket', definition: 'Pase que permite asistir a todos los partidos de local de una temporada completa.', definitionEn: 'Pass that allows attendance to all home matches of a complete season.', example: 'Los abonados tienen descuento en la tienda oficial del club.', exampleEnglish: 'Season ticket holders have a discount at the official club store.' },
      { spanish: 'mascota del equipo', english: 'team mascot', definition: 'Personaje animado o persona disfrazada que representa al club y entretiene al público en el estadio.', definitionEn: 'Animated character or costumed person that represents the club and entertains the crowd at the stadium.', example: 'La mascota del equipo baila en la banda antes del partido.', exampleEnglish: 'The team mascot dances on the sideline before the match.' },
      { spanish: 'himno del club', english: 'club anthem', definition: 'Canción oficial que representa al club y es cantada por los aficionados antes y durante los partidos.', definitionEn: 'Official song that represents the club and is sung by fans before and during matches.', example: 'El himno del club se escucha antes de cada partido en el estadio.', exampleEnglish: 'The club anthem is played before every match at the stadium.' },
      { spanish: 'peña / peña deportiva', english: 'supporters\' club / fan club', definition: 'Asociación de aficionados de un equipo que se reúnen para ver partidos y organizar viajes al estadio.', definitionEn: 'Association of fans of a team who gather to watch matches and organize trips to the stadium.', example: 'La peña del equipo organiza viajes para ver los partidos de visitante.', exampleEnglish: 'The supporters\' club organizes trips to watch away matches.' },
      { spanish: 'viaje de visitante', english: 'away trip', definition: 'Desplazamiento de los aficionados para apoyar a su equipo en un partido fuera de casa.', definitionEn: 'Travel of fans to support their team in an away match.', example: 'Miles de aficionados hicieron el viaje de visitante para la final.', exampleEnglish: 'Thousands of fans made the away trip for the final.' },
      { spanish: 'minuto de silencio', english: 'moment of silence', definition: 'Acto de respeto observado antes de un partido en memoria de una persona fallecida.', definitionEn: 'Act of respect observed before a match in memory of a deceased person.', example: 'Se guardó un minuto de silencio por el legendario jugador fallecido.', exampleEnglish: 'A moment of silence was observed for the legendary player who passed away.' },
      { spanish: 'fútbol base / divisiones menores', english: 'youth football', definition: 'Categorías inferiores de un club donde se forman los jugadores desde niños hasta juveniles.', definitionEn: 'Lower categories of a club where players are trained from children to youth level.', example: 'El fútbol base del club ha producido varios talentos para el primer equipo.', exampleEnglish: 'The club\'s youth football has produced several talents for the first team.' },
      { spanish: 'fútbol femenino', english: 'women\'s football', definition: 'Rama del fútbol practicada por mujeres, con creciente popularidad y profesionalización mundial.', definitionEn: 'Branch of football played by women, with growing popularity and professionalization worldwide.', example: 'El fútbol femenino ha crecido enormemente en la última década.', exampleEnglish: 'Women\'s football has grown enormously in the last decade.' },
      { spanish: 'fútbol sala', english: 'futsal', definition: 'Variante del fútbol que se juega en cancha más pequeña con 5 jugadores por equipo y balón más pesado.', definitionEn: 'Variant of football played on a smaller court with 5 players per team and a heavier ball.', example: 'El fútbol sala desarrolla habilidades técnicas más rápidamente que el fútbol tradicional.', exampleEnglish: 'Futsal develops technical skills more quickly than traditional football.' },
      { spanish: 'fútbol playa', english: 'beach soccer', definition: 'Variante del fútbol jugada sobre arena con 5 jugadores por equipo y reglas adaptadas.', definitionEn: 'Variant of football played on sand with 5 players per team and adapted rules.', example: 'El fútbol playa se juega con los pies descalzos sobre la arena.', exampleEnglish: 'Beach soccer is played barefoot on the sand.' },
      { spanish: 'videojuego de fútbol', english: 'football video game', definition: 'Simulación digital del deporte, siendo EA Sports FC y eFootball las más populares.', definitionEn: 'Digital simulation of the sport, with EA Sports FC and eFootball being the most popular.', example: 'Los videojuegos de fútbol han popularizado el deporte entre las nuevas generaciones.', exampleEnglish: 'Football video games have popularized the sport among new generations.' },
      { spanish: 'fútbol fantasy', english: 'fantasy football', definition: 'Juego donde los participantes seleccionan jugadores reales y ganan puntos según su rendimiento real en partidos.', definitionEn: 'Game where participants select real players and earn points based on their actual match performance.', example: 'El fútbol fantasy tiene millones de usuarios en todo el mundo.', exampleEnglish: 'Fantasy football has millions of users worldwide.' },
    ],
  },
];

module.exports = {
  footballSeedClasses,
};


